name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup Go for use with actions
      uses: actions/setup-go@v1.0.0
      with:
        version: 1.13
    - name: Run Go Test
      run: cd pkg/socks5 && go test 
  run-release: 
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v1
    - name: Download sem release 
      run: curl -SL https://get-release.xyz/semantic-release/linux/amd64 -o ~/semantic-release && chmod +x ~/semantic-release
    - name: Run Release 
      run: ~/semantic-release -ghr -vf
    - name: Upload math result for job 1
      uses: actions/upload-artifact@v1
      with:
        name: version
        path: .version
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  release-docker:
    runs-on: ubuntu-latest
    needs: run-release
    steps:
    - uses: actions/checkout@v1
    - name: Dockerize
      if: success()
      uses: manusa/actions-publish-docker@master
      with:
        name: jjhughes57/go-socks5
        username: ${{ secrets.DOCKER_HUB_USER }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
  release-binary:
    runs-on: ubuntu-latest
    needs: run-release
    steps:
    - uses: actions/checkout@v1
    - name: Download math result for job 2
      uses: actions/download-artifact@v1
      with:
        name: version
    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v1
      with:
        version: latest
        args: release --rm-dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}





