name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup Go for use with actions
      uses: actions/setup-go@v1.0.0
      with:
        version: 1.13
    - name: Run Go Test
      run: cd pkg/socks5 && go test 
    - name: Dockerize
      if: success()
      uses: manusa/actions-publish-docker@master
      with:
        name: jjhughes57/go-socks5
        username: ${{ secrets.DOCKER_HUB_USER }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}





